### ISSUE TITLE
Sending a Transaction fails with 'Chia responded with unsuccessful' and 'ValueError: An integer amount or fee is required (too many decimals)'

### ISSUE THREAD

**Issue by grayfallstown** [Playwo/ChiaRPC.Net#11]
Tested with Chia Forks Goji and Flax, sending the transaction via CLI works for both.

Exception in Application:

```
System.Net.Http.HttpRequestException: Chia responded with unsuccessful
   at ChiaRPC.Clients.ChiaRPCClient.PostAsyncRaw[T](Uri requestUri, Object parameters, Boolean throwOnError) in C:\Users\mk\IdeaProjects\ChiaRPC.Net\ChiaRPC.Net\Clients\ChiaRPCClient.cs:line 88
   at ChiaRPC.Clients.WalletRPCClient.SendTransactionAsync(UInt32 walletId, UInt64 amount, UInt64 fee, String targetAddress) in C:\Users\mk\IdeaProjects\ChiaRPC.Net\ChiaRPC.Net\Clients\Wallet\WalletRPCClient.cs:line 89
```

Log from Goji itself:

```
2021-07-11T18:42:32.524 wallet goji.rpc.rpc_server        : WARNING  Error while handling message: Traceback (most recent call last):
  File "goji\rpc\rpc_server.py", line 81, in inner
  File "goji\rpc\wallet_rpc_api.py", line 555, in send_transaction
ValueError: An integer amount or fee is required (too many decimals)
```

```
var walletClient = walletService.WalletClients["Goji-XGJ"];
var targetAddress = "xgj1rdeq86xprttp3wlk699jwcpa92c02u2jel2wm8f68r6s6qe9fugsw72yrx";
// test if walletClient work in general
foreach (var wallet in await walletClient.GetWalletsAsync())
    Console.WriteLine(wallet.Id); // it does
var transactionRecord = await walletClient.SendTransactionAsync(1, 1000, 10, targetAddress);
```

**Comment by grayfallstown** [comment]
I just tested this against chia 1.2, same result:

```
2021-07-11T18:52:16.468 wallet chia.rpc.rpc_server        : WARNING  Error while handling message: Traceback (most recent call last):
  File "chia\rpc\rpc_server.py", line 81, in inner
  File "chia\rpc\wallet_rpc_api.py", line 706, in send_transaction
ValueError: An integer amount or fee is required (too many decimals)
```

**Comment by Playwo** [comment]
Yeah I know the issue, it's just very weird as the input actually are ulongs and therefore have no decimals. 
Probably something with the serialization, will look at it later.

**Comment by Playwo** [comment]
Fixed with your PR, thanks
