### ISSUE TITLE
help,ssl error

### ISSUE THREAD

**Issue by yuhaiqing0707** [Playwo/ChiaRPC.Net#2]
![image](https://user-images.githubusercontent.com/23378168/121318814-2d4b5880-c93e-11eb-98d7-e75159e9af34.png)

**Comment by Playwo** [comment]
Are you on Windows or Linux?

**Comment by yuhaiqing0707** [comment]
Windows

**Comment by yuhaiqing0707** [comment]
> 您使用的是 Windows 还是 Linux？

Windows

**Comment by grayfallstown** [comment]
This is the inner exception thrown on Windows:
```
System.ComponentModel.Win32Exception "No credentials are available in the security package"
   at System.Net.SSPIWrapper.AcquireCredentialsHandle(ISSPIInterface secModule, String package, CredentialUse intent, SCH_CREDENTIALS* scc)
   at System.Net.Security.SslStreamPal.AcquireCredentialsHandle(CredentialUse credUsage, SCH_CREDENTIALS* secureCredential)
   at System.Net.Security.SslStreamPal.AcquireCredentialsHandleSchCredentials(X509Certificate certificate, SslProtocols protocols, EncryptionPolicy policy, Boolean isServer)
   at System.Net.Security.SslStreamPal.AcquireCredentialsHandle(SslStreamCertificateContext certificateContext, SslProtocols protocols, EncryptionPolicy policy, Boolean isServer)
   at System.Net.Security.SecureChannel.AcquireClientCredentials(Byte[]& thumbPrint)
   at System.Net.Security.SecureChannel.GenerateToken(ReadOnlySpan`1 inputBuffer, Byte[]& output)
   at System.Net.Security.SecureChannel.NextMessage(ReadOnlySpan`1 incomingBuffer)
   at System.Net.Security.SslStream.ProcessBlob(Int32 frameSize)
   at System.Net.Security.SslStream.ReceiveBlobAsync[TIOAdapter](TIOAdapter adapter)
   at System.Net.Security.SslStream.ForceAuthenticationAsync[TIOAdapter](TIOAdapter adapter, Boolean receiveFirst, Byte[] reAuthenticationData, Boolean isApm)
   at System.Net.Http.ConnectHelper.EstablishSslConnectionAsyncCore(Boolean async, Stream stream, SslClientAuthenticationOptions sslOptions, CancellationToken cancellationToken)"	string
```

**Comment by grayfallstown** [comment]
Seems to be a known issue: https://github.com/dotnet/runtime/issues/23749#issuecomment-388231655
They are talking about Workarounds, but some links are dead.

**Comment by Playwo** [comment]
Yep I found that too, I will do some testing later.

**Comment by Playwo** [comment]
I used the workaround described in the dotnet issue and it has worked for me.
If you still run into issues please reopen this.
