### ISSUE TITLE
Received an unexpected EOF or 0 bytes from the transport stream.

### ISSUE THREAD

**Issue by grayfallstown** [Playwo/ChiaRPC.Net#8]
I cannot connect to my Chia instance on my Windows system.
The whole thing works for most Chia Forks since #2 was fixed, but not for Chia itself.
Accessing Chia via the CLI works, which uses the RPC Port as far as I know.

```
System.Net.Http.HttpRequestException: The SSL connection could not be established, see inner exception.
 ---> System.IO.IOException:  Received an unexpected EOF or 0 bytes from the transport stream.
   at System.Net.Security.SslStream.<FillHandshakeBufferAsync>g__InternalFillHandshakeBufferAsync|182_0[TIOAdapter](TIOAdapter adap, ValueTask`1 task, Int32 minSize)
   at System.Net.Security.SslStream.ReceiveBlobAsync[TIOAdapter](TIOAdapter adapter)
   at System.Net.Security.SslStream.ForceAuthenticationAsync[TIOAdapter](TIOAdapter adapter, Boolean receiveFirst, Byte[] reAuthenticationData, Boolean isApm)
   at System.Net.Http.ConnectHelper.EstablishSslConnectionAsyncCore(Boolean async, Stream stream, SslClientAuthenticationOptions sslOptions, CancellationToken cancellationToken)
   --- End of inner exception stack trace ---
   at System.Net.Http.ConnectHelper.EstablishSslConnectionAsyncCore(Boolean async, Stream stream, SslClientAuthenticationOptions sslOptions, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.ConnectAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.CreateHttp11ConnectionAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.GetHttpConnectionAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.SendWithRetryAsync(HttpRequestMessage request, Boolean async, Boolean doRequestAuth, CancellationToken cancellationToken)
   at System.Net.Http.RedirectHandler.SendAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
   at System.Net.Http.HttpClient.SendAsyncCore(HttpRequestMessage request, HttpCompletionOption completionOption, Boolean async, Boolean emitTelemetryStartStop, CancellationToken cancellationToken)
   at ChiaRPC.Clients.ChiaRPCClient.PostAsyncRaw[T](Uri requestUri, Object parameters, Boolean throwOnError) in C:\Users\mk\IdeaProjects\FaucetForChiaForks\ChiaRPC.Net\ChiaRPC.Net\Clients\ChiaRPCClient.cs:line 82
   at ChiaRPC.Clients.WalletRPCClient.GetWalletsAsync() in C:\Users\mk\IdeaProjects\FaucetForChiaForks\ChiaRPC.Net\ChiaRPC.Net\Clients\Wallet\WalletRPCClient.cs:line 62
   at ChiaManager.ChiaManager.<>c__DisplayClass13_1.<<Status>b__1>d.MoveNext() in C:\Users\mk\IdeaProjects\FaucetForChiaForks\ChiaManager\ChiaManager.cs:line 108
```

**Comment by Playwo** [comment]
I cannot reproduce this, can you please provide 
- Your chia version
- The endpoint used

**Comment by grayfallstown** [comment]
Chia version 1.1.7, the official, unmodified release from their Github.

The endpoint is on my local network, with no easy or secure way to make it accessible from the outside (My ISP uses double NAT to reuse public IPs for multiple customers, preventing port forwarding in the process).

Currently trying to figure out a good way to debug this locally.

**Comment by Playwo** [comment]
Hmm I tried to replicate it with a fresh installation of the latest release (1.2.0) for both the node and wallet rpc interfaces. 
Could not get the error in any of those.
If you find a way to reproduce it let me know.

**Comment by grayfallstown** [comment]
I deleted my config.yaml and ssl folder. Works now. I am still not sure what caused it.
