### ISSUE TITLE
ChainGreen: The JSON value could not be converted to System.UInt64. Path: $.blockchain_state.peak.weight 

### ISSUE THREAD

**Issue by grayfallstown** [Playwo/ChiaRPC.Net#9]
While this library works well for most chia forks without any code changes, I do get a JSON parse error while trying to get the blockchainstate on ChainGreen.

It cannot convert the value at $.blockchain_state.peak.weight to UInt64. The value is 289894.

The Exception thrown:
```
 System.Text.Json.JsonException: The JSON value could not be converted to System.UInt64. Path: $.blockchain_state.peak.weight | LineNumber: 0 | BytePositionInLine: 1661.
 ---> System.FormatException: Either the JSON value is not in a supported format, or is out of bounds for a UInt64.
   at System.Text.Json.Utf8JsonReader.GetUInt64()
   at System.Text.Json.Serialization.Converters.UInt64Converter.ReadNumberWithCustomHandling(Utf8JsonReader& reader, JsonNumberHandling handling)
   at System.Text.Json.Serialization.JsonConverter`1.TryRead(Utf8JsonReader& reader, Type typeToConvert, JsonSerializerOptions options, ReadStack& state, T& value)
   at System.Text.Json.JsonPropertyInfo`1.ReadJsonAndSetMember(Object obj, ReadStack& state, Utf8JsonReader& reader)
   at System.Text.Json.Serialization.Converters.ObjectDefaultConverter`1.OnTryRead(Utf8JsonReader& reader, Type typeToConvert, JsonSerializerOptions options, ReadStack& state, T& value)
   at System.Text.Json.Serialization.JsonConverter`1.TryRead(Utf8JsonReader& reader, Type typeToConvert, JsonSerializerOptions options, ReadStack& state, T& value)
   at System.Text.Json.JsonPropertyInfo`1.ReadJsonAndSetMember(Object obj, ReadStack& state, Utf8JsonReader& reader)
   at System.Text.Json.Serialization.Converters.ObjectDefaultConverter`1.OnTryRead(Utf8JsonReader& reader, Type typeToConvert, JsonSerializerOptions options, ReadStack& state, T& value)
   at System.Text.Json.Serialization.JsonConverter`1.TryRead(Utf8JsonReader& reader, Type typeToConvert, JsonSerializerOptions options, ReadStack& state, T& value)
   at System.Text.Json.JsonPropertyInfo`1.ReadJsonAndSetMember(Object obj, ReadStack& state, Utf8JsonReader& reader)
   at System.Text.Json.Serialization.Converters.ObjectDefaultConverter`1.OnTryRead(Utf8JsonReader& reader, Type typeToConvert, JsonSerializerOptions options, ReadStack& state, T& value)
   at System.Text.Json.Serialization.JsonConverter`1.TryRead(Utf8JsonReader& reader, Type typeToConvert, JsonSerializerOptions options, ReadStack& state, T& value)
   at System.Text.Json.Serialization.JsonConverter`1.ReadCore(Utf8JsonReader& reader, JsonSerializerOptions options, ReadStack& state)
   --- End of inner exception stack trace ---
   at System.Text.Json.ThrowHelper.ReThrowWithPath(ReadStack& state, Utf8JsonReader& reader, Exception ex)
   at System.Text.Json.Serialization.JsonConverter`1.ReadCore(Utf8JsonReader& reader, JsonSerializerOptions options, ReadStack& state)
   at System.Text.Json.JsonSerializer.ReadCore[TValue](JsonConverter jsonConverter, Utf8JsonReader& reader, JsonSerializerOptions options, ReadStack& state)
   at System.Text.Json.JsonSerializer.ReadCore[TValue](JsonReaderState& readerState, Boolean isFinalBlock, ReadOnlySpan`1 buffer, JsonSerializerOptions options, ReadStack& state, JsonConverter converterBase)
   at System.Text.Json.JsonSerializer.ReadAsync[TValue](Stream utf8Json, Type returnType, JsonSerializerOptions options, CancellationToken cancellationToken)
   at System.Net.Http.Json.HttpContentJsonExtensions.ReadFromJsonAsyncCore[T](HttpContent content, Encoding sourceEncoding, JsonSerializerOptions options, CancellationToken cancellationToken)
   at ChiaRPC.Clients.ChiaRPCClient.PostAsyncRaw[T](Uri requestUri, Object parameters, Boolean throwOnError) in C:\Users\mk\IdeaProjects\FaucetForChiaForks\ChiaRPC.Net\ChiaRPC.Net\Clients\ChiaRPCClient.cs:line 86
   at ChiaRPC.Clients.NodeRPCClient.GetBlockchainStateAsync() in C:\Users\mk\IdeaProjects\FaucetForChiaForks\ChiaRPC.Net\ChiaRPC.Net\Clients\Node\NodeRPCClient.cs:line 18
   at ChiaManager.ChiaManager.<>c__DisplayClass13_2.<<Status>b__3>d.MoveNext() in C:\Users\mk\IdeaProjects\FaucetForChiaForks\ChiaManager\ChiaManager.cs:line 163
```

The JSON this is all about:
```
{
   "blockchain_state":{
      "difficulty":4098979348348928,
      "genesis_challenge_initialized":true,
      "mempool_size":1,
      "peak":{
         "challenge_block_info_hash":"0x4d8c52c743f888b6a4d9b3b3059df0ea6e3d2b3db866b6e2828d36d0317ea171",
         "challenge_vdf_output":{
            "data":"0x03008370a01709da6b20adaa1a5e339d5907e3bbc77908fab2fd0b576f08e4bf314d4bd84408bd883d2f35678ad7d0a22fc1ade2563c437027828cebe5e416af92146b13350a45b33b90aaef667c452a5785f1fd963620d1527dac94d5eb03a1cd180500"
         },
         "deficit":0,
         "farmer_puzzle_hash":"0xfc351ea69d1223596a56683d3878e0e9a2781ed44549bfb97a10e2cdb65fac38",
         "fees":null,
         "finished_challenge_slot_hashes":null,
         "finished_infused_challenge_slot_hashes":null,
         "finished_reward_slot_hashes":null,
         "header_hash":"0x561c507204a05f8b3986fb4b7bc05a83506b3a43524d59f7c7d8bf259643b910",
         "height":289894,
         "infused_challenge_vdf_output":{
            "data":"0x0300bde834cc8f49ff3eda3a386c8bf8021632faa40e0b5f80eccb3df4f291af0906938517f05ea2d7c6dae6c8c97f33ea97c22f083aa4ccd3e87e88b186a67a4c3e1cb05f6dd7486fd01403f41dc489656a28cf3a7a515e550d8b9896b6002afc150100"
         },
         "overflow":false,
         "pool_puzzle_hash":"0xfc351ea69d1223596a56683d3878e0e9a2781ed44549bfb97a10e2cdb65fac38",
         "prev_hash":"0x6e59b0e2d57e0ab5d2f3e843278de04890a00cc3fa17de766b4a37c2702af792",
         "prev_transaction_block_hash":null,
         "prev_transaction_block_height":289893,
         "required_iters":383030,
         "reward_claims_incorporated":null,
         "reward_infusion_new_challenge":"0x9222ae2ff762ce64f07f77595506008d41e7fcce61d704b778cd83584d3a71db",
         "signage_point_index":50,
         "sub_epoch_summary_included":null,
         "sub_slot_iters":79167488,
         "timestamp":null,
         "total_iters":255293836342,
         "weight":192843331376204237844
      },
      "space":663260762976726784,
      "sub_slot_iters":79167488,
      "sync":{
         "sync_mode":false,
         "sync_progress_height":0,
         "sync_tip_height":0,
         "synced":true
      }
   },
   "success":true
}
```

**Comment by Playwo** [comment]
I've changed the type to BigInteger, should be fixed now
